spring.application.name=homosphere-backend


# PostgreSQL connection using environment variables with defaults for development
spring.datasource.url=jdbc:postgresql://${DB_HOMOSPHERE_HOST:aws-1-eu-west-1.pooler.supabase.com}:${DB_HOMOSPHERE_PORT:5432}/${DB_HOMOSPHERE_NAME:postgres?sslmode=require}
spring.datasource.username=${DB_HOMOSPHERE_USERNAME:postgres.njergtgoucwagfkijaqu}
spring.datasource.password=${DB_HOMOSPHERE_PASSWORD:hBWojTTa2lMS1Vna}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# server port
server.port = ${HOMOSPHERE_PORT:8080}


# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool
spring.datasource.hikari.connection-test-query=SELECT 1


# supabase JWT

supabase.jwt.secret=${HOMOSPHERE_JWT_SECRET:mfAdvQoSZ0dtubdPhkMTIGDLNzoEwLqTpEu7pP0ACtdaWINcRXRFJDa4U4tb6926g4uFmh63RVWZ9s7aPAzmjA==}
supabase.service.role.key=${HOMOSPHERE_SUPABASE_SERVICE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZXJndGdvdWN3YWdma2lqYXF1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MzY2OTgwMSwiZXhwIjoyMDc5MjQ1ODAxfQ.OGoijHyEHg3E8GQXaJzl7IQy3UImDxvsXPEF-FLWwB8}
supabase.url=${HOMOSPHERE_SUPABASE_URL:https://njergtgoucwagfkijaqu.supabase.co}/

# CORS Configuration
# export HOMOSPHERE_CORS_ALLOWED_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
cors.allowed.origins=${HOMOSPHERE_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:4200}


#cloud flare configration
cloudflare.r2.accessKey=${HOMOSPHERE_CLOUDFLARE_R2_ACCESS_KEY_ID:53a1df5ea13574fef5fc7f3d5c2595a0}
cloudflare.r2.secretKey=${HOMOSPHERE_CLOUDFLARE_R2_SECRET_ACCESS_KEY:75afdd4f7edb10e5bb217877eded8d967b26f053417bb26299383d53e6d55711}
cloudflare.r2.bucket=${HOMOSPHERE_CLOUDFLARE_R2_BUCKET_NAME:homosphere-properties-images}
cloudflare.r2.account-id=${HOMOSPHERE_CLOUDFLARE_R2_ACCOUNT_ID:0385e42829fa17faa3577a19b830754f}
cloudflare.r2.region=auto
cloudflare.r2.endpoint=https://${cloudflare.r2.account-id}.r2.cloudflarestorage.com/
cloudflare.r2.public-domain=${HOMOSPHERE_CLOUDFLARE_R2_PUBLIC_DOMAIN:https://pub-5fe480d20f5b4a3e9d119df2e1376fbc.r2.dev}
