spring.application.name=homosphere-backend


# PostgreSQL connection using environment variables with defaults for development
spring.datasource.url=jdbc:postgresql://${DB_HOMOSPHERE_HOST:aws-1-eu-west-1.pooler.supabase.com}:${DB_HOMOSPHERE_PORT:6543}/${DB_HOMOSPHERE_NAME:postgres?sslmode=require}
spring.datasource.username=${DB_HOMOSPHERE_USERNAME:postgres.njergtgoucwagfkijaqu}
spring.datasource.password=${DB_HOMOSPHERE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# jpa 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# server port
server.port = ${HOMOSPHERE_PORT:8080}


# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool


# supabase JWT 

supabase.jwt.secret=${HOMOSPHERE_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D635166546A576E5A7234753778214125442A472D4B6150645367566B59703373367639792442264529}
supabase.service.role.key=${HOMOSPHERE_SUPABASE_SERVICE_KEY:your key}
supabase.url=${HOMOSPHERE_SUPABASE_URL:your url}

# CORS Configuration
# export HOMOSPHERE_CORS_ALLOWED_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
cors.allowed.origins=${HOMOSPHERE_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:4200}


#cloud flare configration
cloudflare.r2.accessKey=${HOMOSPHERE_CLOUDFLARE_R2_ACCESS_KEY_ID:dummy-access-key}
cloudflare.r2.secretKey=${HOMOSPHERE_CLOUDFLARE_R2_SECRET_ACCESS_KEY:dummy-secret-key}
cloudflare.r2.bucket=${HOMOSPHERE_CLOUDFLARE_R2_BUCKET_NAME:homosphere-properties-images}
cloudflare.r2.account-id=${HOMOSPHERE_CLOUDFLARE_R2_ACCOUNT_ID:dummy-account-id}
cloudflare.r2.region=auto
cloudflare.r2.endpoint=https://${cloudflare.r2.account-id}.r2.cloudflarestorage.com

