spring.application.name=homosphere-backend


# PostgreSQL connection using environment variables with defaults for development
spring.datasource.url=jdbc:postgresql://${DB_HOMOSPHERE_HOST}:${DB_HOMOSPHERE_PORT}/${DB_HOMOSPHERE_NAME}
spring.datasource.username=${DB_HOMOSPHERE_USERNAME}
spring.datasource.password=${DB_HOMOSPHERE_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# server port
server.port = ${HOMOSPHERE_PORT:8080}


# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool
spring.datasource.hikari.connection-test-query=SELECT 1


# supabase JWT

supabase.jwt.secret=${HOMOSPHERE_JWT_SECRET}
supabase.service.role.key=${HOMOSPHERE_SUPABASE_SERVICE_KEY}
supabase.url=${HOMOSPHERE_SUPABASE_URL}/

# CORS Configuration
# export HOMOSPHERE_CORS_ALLOWED_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
cors.allowed.origins=${HOMOSPHERE_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:4200,http://127.0.0.1:3000,http://localhost:8000}


#cloud flare configration
cloudflare.r2.accessKey=${HOMOSPHERE_CLOUDFLARE_R2_ACCESS_KEY_ID}
cloudflare.r2.secretKey=${HOMOSPHERE_CLOUDFLARE_R2_SECRET_ACCESS_KEY}
cloudflare.r2.bucket=${HOMOSPHERE_CLOUDFLARE_R2_BUCKET_NAME}
cloudflare.r2.account-id=${HOMOSPHERE_CLOUDFLARE_R2_ACCOUNT_ID}
cloudflare.r2.region=auto
cloudflare.r2.endpoint=https://${cloudflare.r2.account-id}.r2.cloudflarestorage.com/
cloudflare.r2.public-domain=${HOMOSPHERE_CLOUDFLARE_R2_PUBLIC_DOMAIN}


# PayPaL
paypal.client-id=${HOM_PAYPAL_CLIENT}
paypal.client-secret=${HOM_PAYPAL_SECRET}
paypal.mode=sandbox